// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/srv/service.proto

package srv

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	pb "github.com/hxuanhung/go-grpc-rest-realworld-example/api/pb"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("api/srv/service.proto", fileDescriptor_36554cfc910dccce) }

var fileDescriptor_36554cfc910dccce = []byte{
	// 339 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xc1, 0xaa, 0x13, 0x31,
	0x18, 0x85, 0xa1, 0x4a, 0xa5, 0xd3, 0x4d, 0x09, 0xb8, 0x70, 0xec, 0x22, 0x8a, 0x4b, 0x33, 0x41,
	0x7d, 0x82, 0xe2, 0xc2, 0xae, 0x2b, 0x8a, 0xe0, 0x42, 0x32, 0x99, 0xdf, 0x24, 0x3a, 0x93, 0x3f,
	0xe6, 0x4f, 0xa6, 0x5d, 0xfb, 0x08, 0xf5, 0x79, 0x7c, 0x0a, 0x5f, 0xc1, 0x07, 0x91, 0x49, 0xc7,
	0xcb, 0xe5, 0xde, 0xae, 0x42, 0xfe, 0x73, 0xf8, 0xce, 0xe1, 0x54, 0x8f, 0x55, 0x70, 0x92, 0xe2,
	0x28, 0x09, 0xe2, 0xe8, 0x34, 0x34, 0x21, 0x62, 0x42, 0xf6, 0x80, 0xe2, 0x58, 0xef, 0x8d, 0x4b,
	0x36, 0xb7, 0x8d, 0xc6, 0x41, 0xda, 0x53, 0x56, 0xde, 0x66, 0x6f, 0xa4, 0x41, 0x61, 0x62, 0xd0,
	0x22, 0x02, 0x25, 0x11, 0x41, 0xf5, 0x47, 0x8c, 0x7d, 0x27, 0xe0, 0xa4, 0x86, 0xd0, 0x83, 0x9c,
	0x78, 0xa1, 0x95, 0x03, 0x10, 0x29, 0x33, 0xe3, 0xea, 0xad, 0x41, 0x34, 0xb3, 0xa8, 0xbc, 0xc7,
	0xa4, 0x92, 0x43, 0x4f, 0xb3, 0xfa, 0xb2, 0x3c, 0x5a, 0x18, 0xf0, 0x82, 0x8e, 0xca, 0x18, 0x88,
	0x12, 0x43, 0x71, 0xdc, 0x77, 0xbf, 0xfe, 0xbd, 0xa8, 0x1e, 0xbd, 0xbf, 0x94, 0x65, 0xdf, 0xaa,
	0xf5, 0x1e, 0x54, 0x9f, 0xec, 0x5b, 0x0b, 0xfa, 0x3b, 0x7b, 0xd2, 0x84, 0xb6, 0x79, 0x07, 0xe9,
	0xd6, 0xed, 0x00, 0x3f, 0x32, 0x50, 0xaa, 0xeb, 0x6b, 0x12, 0x05, 0xf4, 0x04, 0xcf, 0x5f, 0x9c,
	0x77, 0xab, 0x1b, 0xe6, 0xcf, 0x3f, 0x7f, 0x7f, 0x2d, 0x18, 0xdb, 0xc8, 0xf1, 0x95, 0xb4, 0xc5,
	0xfc, 0x45, 0x17, 0xb8, 0xab, 0x36, 0x1f, 0x08, 0xe2, 0x01, 0x8c, 0xa3, 0x14, 0x4b, 0x25, 0xf6,
	0x74, 0xa2, 0xde, 0xbd, 0xfe, 0x8f, 0xdc, 0x5e, 0x17, 0xe7, 0xd0, 0xfa, 0xbc, 0x5b, 0x56, 0x0f,
	0x27, 0xb9, 0x24, 0xae, 0xd9, 0x6a, 0x4a, 0xcc, 0x04, 0x91, 0xea, 0xcf, 0xe7, 0xdd, 0x27, 0xf6,
	0x71, 0x2e, 0xc4, 0x3b, 0x20, 0x1d, 0x5d, 0xd9, 0x83, 0x0b, 0xc1, 0x8f, 0xd6, 0x69, 0xcb, 0xc9,
	0x62, 0xee, 0x3b, 0xee, 0x31, 0xf1, 0x16, 0x78, 0x26, 0xe8, 0xb8, 0xf3, 0x3c, 0xf4, 0x4a, 0x03,
	0xc7, 0xaf, 0x3c, 0x59, 0xe0, 0x1d, 0xea, 0x3c, 0x80, 0xbf, 0xac, 0xc7, 0x35, 0x0e, 0xd3, 0xe7,
	0x59, 0xbb, 0x2c, 0x33, 0xbe, 0xf9, 0x17, 0x00, 0x00, 0xff, 0xff, 0xa2, 0x12, 0xb1, 0x1b, 0xfa,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServiceClient interface {
	// Check the health of the acre processor. This is used by load balancers to check end-to-end service health. Not yet implemented.
	HealthCheck(ctx context.Context, in *pb.GetHealthCheckRequest, opts ...grpc.CallOption) (*pb.GetHealthCheckResponse, error)
	UserRegistration(ctx context.Context, in *pb.UserRegistrationRequest, opts ...grpc.CallOption) (*pb.UserRegistrationResponse, error)
}

type serviceClient struct {
	cc *grpc.ClientConn
}

func NewServiceClient(cc *grpc.ClientConn) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) HealthCheck(ctx context.Context, in *pb.GetHealthCheckRequest, opts ...grpc.CallOption) (*pb.GetHealthCheckResponse, error) {
	out := new(pb.GetHealthCheckResponse)
	err := c.cc.Invoke(ctx, "/srv.Service/HealthCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) UserRegistration(ctx context.Context, in *pb.UserRegistrationRequest, opts ...grpc.CallOption) (*pb.UserRegistrationResponse, error) {
	out := new(pb.UserRegistrationResponse)
	err := c.cc.Invoke(ctx, "/srv.Service/UserRegistration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceServer is the server API for Service service.
type ServiceServer interface {
	// Check the health of the acre processor. This is used by load balancers to check end-to-end service health. Not yet implemented.
	HealthCheck(context.Context, *pb.GetHealthCheckRequest) (*pb.GetHealthCheckResponse, error)
	UserRegistration(context.Context, *pb.UserRegistrationRequest) (*pb.UserRegistrationResponse, error)
}

// UnimplementedServiceServer can be embedded to have forward compatible implementations.
type UnimplementedServiceServer struct {
}

func (*UnimplementedServiceServer) HealthCheck(ctx context.Context, req *pb.GetHealthCheckRequest) (*pb.GetHealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (*UnimplementedServiceServer) UserRegistration(ctx context.Context, req *pb.UserRegistrationRequest) (*pb.UserRegistrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserRegistration not implemented")
}

func RegisterServiceServer(s *grpc.Server, srv ServiceServer) {
	s.RegisterService(&_Service_serviceDesc, srv)
}

func _Service_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.GetHealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/srv.Service/HealthCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).HealthCheck(ctx, req.(*pb.GetHealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_UserRegistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.UserRegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).UserRegistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/srv.Service/UserRegistration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).UserRegistration(ctx, req.(*pb.UserRegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Service_serviceDesc = grpc.ServiceDesc{
	ServiceName: "srv.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _Service_HealthCheck_Handler,
		},
		{
			MethodName: "UserRegistration",
			Handler:    _Service_UserRegistration_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/srv/service.proto",
}
