// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/pb/message.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Get health status of services.
type GetHealthCheckRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHealthCheckRequest) Reset()         { *m = GetHealthCheckRequest{} }
func (m *GetHealthCheckRequest) String() string { return proto.CompactTextString(m) }
func (*GetHealthCheckRequest) ProtoMessage()    {}
func (*GetHealthCheckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f674478d14d7f658, []int{0}
}

func (m *GetHealthCheckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHealthCheckRequest.Unmarshal(m, b)
}
func (m *GetHealthCheckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHealthCheckRequest.Marshal(b, m, deterministic)
}
func (m *GetHealthCheckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHealthCheckRequest.Merge(m, src)
}
func (m *GetHealthCheckRequest) XXX_Size() int {
	return xxx_messageInfo_GetHealthCheckRequest.Size(m)
}
func (m *GetHealthCheckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHealthCheckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetHealthCheckRequest proto.InternalMessageInfo

// Health status of services.
type GetHealthCheckResponse struct {
	// The status of the relevant sub services.
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHealthCheckResponse) Reset()         { *m = GetHealthCheckResponse{} }
func (m *GetHealthCheckResponse) String() string { return proto.CompactTextString(m) }
func (*GetHealthCheckResponse) ProtoMessage()    {}
func (*GetHealthCheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f674478d14d7f658, []int{1}
}

func (m *GetHealthCheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHealthCheckResponse.Unmarshal(m, b)
}
func (m *GetHealthCheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHealthCheckResponse.Marshal(b, m, deterministic)
}
func (m *GetHealthCheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHealthCheckResponse.Merge(m, src)
}
func (m *GetHealthCheckResponse) XXX_Size() int {
	return xxx_messageInfo_GetHealthCheckResponse.Size(m)
}
func (m *GetHealthCheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHealthCheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetHealthCheckResponse proto.InternalMessageInfo

func (m *GetHealthCheckResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*GetHealthCheckRequest)(nil), "pb.GetHealthCheckRequest")
	proto.RegisterType((*GetHealthCheckResponse)(nil), "pb.GetHealthCheckResponse")
}

func init() { proto.RegisterFile("api/pb/message.proto", fileDescriptor_f674478d14d7f658) }

var fileDescriptor_f674478d14d7f658 = []byte{
	// 111 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x49, 0x2c, 0xc8, 0xd4,
	0x2f, 0x48, 0xd2, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0x62, 0x2a, 0x48, 0x52, 0x12, 0xe7, 0x12, 0x75, 0x4f, 0x2d, 0xf1, 0x48, 0x4d, 0xcc, 0x29,
	0xc9, 0x70, 0xce, 0x48, 0x4d, 0xce, 0x0e, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x51, 0x32, 0xe0,
	0x12, 0x43, 0x97, 0x28, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x15, 0x12, 0xe3, 0x62, 0x2b, 0x2e, 0x49,
	0x2c, 0x29, 0x2d, 0x96, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0xf2, 0x92, 0xd8, 0xc0, 0xa6,
	0x1a, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x9c, 0x13, 0x94, 0x66, 0x6d, 0x00, 0x00, 0x00,
}
