// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/pb/message.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Get health status of services.
type GetHealthCheckRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHealthCheckRequest) Reset()         { *m = GetHealthCheckRequest{} }
func (m *GetHealthCheckRequest) String() string { return proto.CompactTextString(m) }
func (*GetHealthCheckRequest) ProtoMessage()    {}
func (*GetHealthCheckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f674478d14d7f658, []int{0}
}

func (m *GetHealthCheckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHealthCheckRequest.Unmarshal(m, b)
}
func (m *GetHealthCheckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHealthCheckRequest.Marshal(b, m, deterministic)
}
func (m *GetHealthCheckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHealthCheckRequest.Merge(m, src)
}
func (m *GetHealthCheckRequest) XXX_Size() int {
	return xxx_messageInfo_GetHealthCheckRequest.Size(m)
}
func (m *GetHealthCheckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHealthCheckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetHealthCheckRequest proto.InternalMessageInfo

type UserRegistrationRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Bio                  string   `protobuf:"bytes,3,opt,name=bio,proto3" json:"bio,omitempty"`
	Image                string   `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRegistrationRequest) Reset()         { *m = UserRegistrationRequest{} }
func (m *UserRegistrationRequest) String() string { return proto.CompactTextString(m) }
func (*UserRegistrationRequest) ProtoMessage()    {}
func (*UserRegistrationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f674478d14d7f658, []int{1}
}

func (m *UserRegistrationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRegistrationRequest.Unmarshal(m, b)
}
func (m *UserRegistrationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRegistrationRequest.Marshal(b, m, deterministic)
}
func (m *UserRegistrationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRegistrationRequest.Merge(m, src)
}
func (m *UserRegistrationRequest) XXX_Size() int {
	return xxx_messageInfo_UserRegistrationRequest.Size(m)
}
func (m *UserRegistrationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRegistrationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRegistrationRequest proto.InternalMessageInfo

func (m *UserRegistrationRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserRegistrationRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserRegistrationRequest) GetBio() string {
	if m != nil {
		return m.Bio
	}
	return ""
}

func (m *UserRegistrationRequest) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *UserRegistrationRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type User struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Bio                  string   `protobuf:"bytes,4,opt,name=bio,proto3" json:"bio,omitempty"`
	Image                string   `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	PasswordHash         string   `protobuf:"bytes,6,opt,name=passwordHash,proto3" json:"passwordHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_f674478d14d7f658, []int{2}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetBio() string {
	if m != nil {
		return m.Bio
	}
	return ""
}

func (m *User) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *User) GetPasswordHash() string {
	if m != nil {
		return m.PasswordHash
	}
	return ""
}

// Health status of services.
type GetHealthCheckResponse struct {
	// The status of the relevant sub services.
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHealthCheckResponse) Reset()         { *m = GetHealthCheckResponse{} }
func (m *GetHealthCheckResponse) String() string { return proto.CompactTextString(m) }
func (*GetHealthCheckResponse) ProtoMessage()    {}
func (*GetHealthCheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f674478d14d7f658, []int{3}
}

func (m *GetHealthCheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHealthCheckResponse.Unmarshal(m, b)
}
func (m *GetHealthCheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHealthCheckResponse.Marshal(b, m, deterministic)
}
func (m *GetHealthCheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHealthCheckResponse.Merge(m, src)
}
func (m *GetHealthCheckResponse) XXX_Size() int {
	return xxx_messageInfo_GetHealthCheckResponse.Size(m)
}
func (m *GetHealthCheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHealthCheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetHealthCheckResponse proto.InternalMessageInfo

func (m *GetHealthCheckResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type UserRegistrationResponse struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Bio                  string   `protobuf:"bytes,3,opt,name=bio,proto3" json:"bio,omitempty"`
	Image                string   `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	Token                string   `protobuf:"bytes,6,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRegistrationResponse) Reset()         { *m = UserRegistrationResponse{} }
func (m *UserRegistrationResponse) String() string { return proto.CompactTextString(m) }
func (*UserRegistrationResponse) ProtoMessage()    {}
func (*UserRegistrationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f674478d14d7f658, []int{4}
}

func (m *UserRegistrationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRegistrationResponse.Unmarshal(m, b)
}
func (m *UserRegistrationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRegistrationResponse.Marshal(b, m, deterministic)
}
func (m *UserRegistrationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRegistrationResponse.Merge(m, src)
}
func (m *UserRegistrationResponse) XXX_Size() int {
	return xxx_messageInfo_UserRegistrationResponse.Size(m)
}
func (m *UserRegistrationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRegistrationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserRegistrationResponse proto.InternalMessageInfo

func (m *UserRegistrationResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserRegistrationResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserRegistrationResponse) GetBio() string {
	if m != nil {
		return m.Bio
	}
	return ""
}

func (m *UserRegistrationResponse) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *UserRegistrationResponse) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserRegistrationResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*GetHealthCheckRequest)(nil), "pb.GetHealthCheckRequest")
	proto.RegisterType((*UserRegistrationRequest)(nil), "pb.UserRegistrationRequest")
	proto.RegisterType((*User)(nil), "pb.User")
	proto.RegisterType((*GetHealthCheckResponse)(nil), "pb.GetHealthCheckResponse")
	proto.RegisterType((*UserRegistrationResponse)(nil), "pb.UserRegistrationResponse")
}

func init() { proto.RegisterFile("api/pb/message.proto", fileDescriptor_f674478d14d7f658) }

var fileDescriptor_f674478d14d7f658 = []byte{
	// 270 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x92, 0x4d, 0x4e, 0xfb, 0x30,
	0x10, 0xc5, 0x95, 0x4f, 0xfd, 0xff, 0x23, 0x40, 0xc8, 0x2a, 0xad, 0xc5, 0x0a, 0x79, 0xc5, 0x8a,
	0x22, 0x71, 0x04, 0x16, 0x74, 0x1d, 0x89, 0x03, 0x4c, 0xc8, 0x28, 0xb1, 0xda, 0xc4, 0x26, 0xe3,
	0x88, 0x63, 0xb0, 0xe1, 0x0c, 0x9c, 0x13, 0xd9, 0x71, 0x11, 0x85, 0xb2, 0x66, 0x97, 0x37, 0x6f,
	0x3e, 0x7e, 0x79, 0x32, 0x2c, 0xd0, 0xea, 0xb5, 0xad, 0xd7, 0x3d, 0x31, 0x63, 0x4b, 0x37, 0x76,
	0x34, 0xce, 0x88, 0xd4, 0xd6, 0x6a, 0x05, 0x17, 0x0f, 0xe4, 0x36, 0x84, 0x3b, 0xd7, 0xdd, 0x77,
	0xf4, 0xb4, 0xad, 0xe8, 0x79, 0x22, 0x76, 0xea, 0x35, 0x81, 0xd5, 0x23, 0xd3, 0x58, 0x51, 0xab,
	0xd9, 0x8d, 0xe8, 0xb4, 0x19, 0xa2, 0x27, 0x2e, 0xe1, 0xdf, 0xc4, 0x34, 0x0e, 0xd8, 0x93, 0x4c,
	0xae, 0x92, 0xeb, 0xff, 0xd5, 0xa7, 0x16, 0x0b, 0x28, 0xa8, 0x47, 0xbd, 0x93, 0x69, 0x30, 0x66,
	0x21, 0xce, 0x21, 0xab, 0xb5, 0x91, 0x59, 0xa8, 0xf9, 0x4f, 0xdf, 0xa7, 0x7b, 0x6c, 0x49, 0xe6,
	0x73, 0x5f, 0x10, 0x7e, 0xb3, 0x45, 0xe6, 0x17, 0x33, 0x36, 0xb2, 0x98, 0x37, 0xef, 0xb5, 0x7a,
	0x4b, 0x20, 0xf7, 0x44, 0xe2, 0x0c, 0x52, 0xdd, 0x84, 0xc3, 0xa7, 0x55, 0xaa, 0x9b, 0x03, 0x9c,
	0xf4, 0x37, 0x9c, 0xec, 0x08, 0x4e, 0x7e, 0x04, 0xa7, 0xf8, 0x8a, 0xa3, 0xe0, 0x64, 0x7f, 0x7e,
	0x83, 0xdc, 0xc9, 0x32, 0x98, 0x07, 0x35, 0x75, 0x0b, 0xcb, 0xef, 0x09, 0xb2, 0x35, 0x03, 0x93,
	0x58, 0x42, 0xc9, 0x0e, 0xdd, 0xc4, 0x31, 0xa4, 0xa8, 0xd4, 0x7b, 0x02, 0xf2, 0x67, 0xb4, 0x71,
	0xe8, 0x4f, 0xb2, 0xf5, 0x13, 0xce, 0x6c, 0x69, 0x88, 0x7f, 0x38, 0x8b, 0xba, 0x0c, 0xef, 0xe4,
	0xee, 0x23, 0x00, 0x00, 0xff, 0xff, 0xf1, 0x1a, 0x50, 0x28, 0x3f, 0x02, 0x00, 0x00,
}
